# Database Configuration
database:
  host: "${DB_HOST}"
  port: "${DB_PORT:3307}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME:warranty}"

# Shopify Configuration
shopify:
  shop_domain: "${SHOPIFY_SHOP_DOMAIN}"
  access_token: "${SHOPIFY_ACCESS_TOKEN}"
  api_version: "${SHOPIFY_API_VERSION:2025-10}"
  timeout: "${SHOPIFY_TIMEOUT:30}"

# Processing Configuration
processing:
  max_retries: "${MAX_RETRIES:3}"
  retry_delay: "${RETRY_DELAY:1.0}"
  batch_size: "${BATCH_SIZE:10}"
  rate_limit_per_second: "${RATE_LIMIT_PER_SECOND:2}"

# Logging Configuration
logging:
  level: "${LOG_LEVEL:INFO}"
  file: "${LOG_FILE:logs/product_export.log}"
  max_size: "${LOG_MAX_SIZE:10MB}"
  backup_count: "${LOG_BACKUP_COUNT:5}"

# Image Processing (Placeholder)
images:
  enabled: false
  source_path: "${IMAGE_SOURCE_PATH:/images}"
  upload_method: "staged_upload"
