# Database Configuration
database:
  host: "${DB_HOST}"
  port: "${DB_PORT:3307}"
  user: "${DB_USER}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME:warranty}"

# Shopify Configuration
shopify:
  shop_domain: "${SHOPIFY_SHOP_DOMAIN}"
  access_token: "${SHOPIFY_ACCESS_TOKEN}"
  api_version: "${SHOPIFY_API_VERSION:2025-10}"
  timeout: "${SHOPIFY_TIMEOUT:30}"

# Processing Configuration
processing:
  max_retries: "${MAX_RETRIES:3}"
  retry_delay: "${RETRY_DELAY:1.0}"
  batch_size: "${BATCH_SIZE:10}"
  rate_limit_per_second: "${RATE_LIMIT_PER_SECOND:2}"

# Logging Configuration
logging:
  level: "${LOG_LEVEL:INFO}"
  file: "${LOG_FILE:logs/product_export.log}"
  max_size: "${LOG_MAX_SIZE:10MB}"
  backup_count: "${LOG_BACKUP_COUNT:5}"

# AWS S3 Configuration for Image Processing
aws:
  access_key_id: "${AWS_ACCESS_KEY_ID}"
  secret_access_key: "${AWS_SECRET_ACCESS_KEY}"
  session_token: "${AWS_SESSION_TOKEN}"
  region: "${AWS_REGION:us-east-1}"
  bucket: "${AWS_S3_BUCKET:production-charlesandcolvard-moissanite2-media-import}"

# Image Processing Configuration
images:
  enabled: "${IMAGES_ENABLED:true}"
  base_directory: "${IMAGE_BASE_DIR:sorted-media}"
  min_width: "${IMAGE_MIN_WIDTH:250}"
  min_height: "${IMAGE_MIN_HEIGHT:250}"
  accepted_extensions: [".jpg", ".jpeg", ".png", ".gif", ".webp"]
  variation_suffix: "${IMAGE_VARIATION_SUFFIX:a}"
  max_workers: "${IMAGE_MAX_WORKERS:10}"
